### ISSUE TITLE
Can't save settings

### ISSUE THREAD

**Issue by ctbritt** [nivthefox/foundryvtt-aide#1]
not sure what the issue is. I have my key set, and my models set like so: 
![CleanShot 2024-11-08 at 13 13 51](https://github.com/user-attachments/assets/33e05f42-8f80-498c-b11f-5193020a4472)

But I keep getting this error: 
![CleanShot 2024-11-08 at 13 14 53](https://github.com/user-attachments/assets/16c3b6ba-4747-4009-b40a-0745fe0eee28)

**Comment by nivthefox** [comment]
Ah, yeah I should hide the model settings from this view.  They really can't be changed until you've selected your provider.  Also you don't need to set the Base URLs unless they are different from the default.

I'll try and make this more intuitive in my next release (1.1.1 or 1.2.0)
